test:
  ttl: 604800
  namespace: "cache-money"
  sessions: false
  debug: false
  servers: localhost:11211

development:
  ttl: 604800
  namespace: "cache-money"
  sessions: false
  debug: false
  servers: localhost:11211

production:
  ttl: 604800
  namespace: "cache-money"
  sessions: false
  debug: false
  servers: localhost:11211
